Gradient update in ADAM method to fix the issue #100
1QB-Information-Technologies/ccvm pull request #104
Opened 2023-09-19 18:06 UTC by MehmetC-1QBit

### Description

>  To address [the issue ](https://github.com/1QB-Information-Technologies/ccvm/issues/100#issue-1897028068), two versions of the gradient update in [Adam](https://doi.org/10.48550/arXiv.1412.6980) methods of the solver classes were updated:
- version#1
![grad_assigned](https://github.com/1QB-Information-Technologies/ccvm/assets/82167289/5c1b61a4-478b-4963-a060-24ea6a0558f8)
- version#2
![grad_add_assigned](https://github.com/1QB-Information-Technologies/ccvm/assets/82167289/4f0c205a-cd95-41f7-a4e3-763318a2a1b9)

**To investigate further**
>  ADAM methods in all solvers (`MF, DL, Langevin`) were reflected the change.
>  Demo scripts were updated correspondingly.

**Minor fix:**
> - Fixed issue with `examples/ccvm_boxqp_plot.py`
> - Updated `examples/README.md`

### References
> Closes #100

### Testing
> Demo scripts in `examples/` can be executed for sample instance when `solve_type="Adam"`
is selected with `hyperparameters=dict( beta1=0.9,  beta2=0.999,  alpha=0.2,  which_adam="ASSIGN")`.
Here one can choose either `which_adam="ASSIGN"` or `which_adam="ADD_ASSIGN"` for the desired gradient update.
   
### Checklist

- [x] I have added documentation for new/changed functionality in this PR
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `main`

2023-09-20 18:31 UTC, FarhadK-1QBit approved these changes

2023-09-23 02:01 UTC, Estella-Wang-1qbit requested changes
Great job! 👍 I left some comment for your consideration. Most of them pertain to our coding guidelines and aesthetics. If you have any questions or need further clarification on my comments, please feel free to ask. Once these comments are addressed, I'll be ready to approve it.

2023-09-25 14:36 UTC, MehmetC-1QBit commented on ccvm_simulators/solvers/dl_solver.py
> +                gradc, grads, mhatc, vhatc, mhats, vhats
Thanks for bringing this up. Before addressing your question I would like you to keep in mind that `_solve_adam()` methods in the sover classes are experimental and the redundancies including the one you pointed out will be addressed in later issues/PRs.

**Let's get back to your question:**  This function (`update_grads_with_moment2_assign` in line 585) and the other function (`update_grads_with_moment2_addassign` in line 593) are  conditionally called in between 665-668 based on the choice (lines 608-618). For the sake of a single call in line 665-668 we need to keep `c_grads` and  `s_grads` as an argument.  
I hope my answer addresses your question.

2023-09-25 14:39 UTC, MehmetC-1QBit commented on ccvm_simulators/solvers/dl_solver.py
> +        def update_grads_without_moment2_assign(gradc, grads, mhatc, mhats):
I suppose my answer in the previous comment address this one as well

2023-09-25 14:51 UTC, MehmetC-1QBit commented on ccvm_simulators/solvers/dl_solver.py
> +                c_grads, s_grads =\
You are right, I fixed it. 
BTW I started using black with this project. Bu I am having a hard time in understanding why black sometimes does not hit this time of line breaking.

2023-09-25 14:54 UTC, MehmetC-1QBit commented on ccvm_simulators/solvers/mf_solver.py
> +        def update_grads_with_moment2_addassign(grads, mhat, vhat):
My answer in for `dl_solver.py` also applies here.

2023-09-25 15:17 UTC, MehmetC-1QBit commented on examples/ccvm_boxqp_dl.py
> +                which_adam="ASSIGN", # Temporary flag for selecting desired gradient update either "ASSIGN" or "ADD_ASSIGN" in the Adam method.
Same as in previous comment

2023-09-25 20:49 UTC, Estella-Wang-1qbit commented on ccvm_simulators/solvers/dl_solver.py
> +                gradc, grads, mhatc, vhatc, mhats, vhats
This sounds good. Thanks for the detailed explanation.

2023-09-25 20:51 UTC, Estella-Wang-1qbit commented on ccvm_simulators/solvers/dl_solver.py
> +                c_grads, s_grads =\
Hmm. I haven't had this issue. But I guess when you try running `black` again, it fixed the backslash issue right?

2023-09-25 20:52 UTC, Estella-Wang-1qbit commented on ccvm_simulators/solvers/dl_solver.py
> +                c_grads, s_grads =\
We can look into this deeper if this continue to bother you in the future.

2023-09-25 20:57 UTC, Estella-Wang-1qbit approved these changes
Thank you Mehmet. Great work! 👍

2023-09-25 21:04 UTC, merged

2023-09-25 21:09 UTC, MehmetC-1QBit commented on ccvm_simulators/solvers/langevin_solver.py
> +                #===============================================================
This was the statement that the method call just below this line replaced it. I should have removed it